export interface Bootcamp {
  id: string
  title: string
  duration: string
  month: string
  category: string
  type: "short-term" | "long-term"
  description: string
  registrationLink?: string
  highlights?: string[]
  takeaways?: string[]
}

export const bootcampCategories = {
  "executive-leadership": "Executive Leadership",
  "professional-dev": "Professional Development",
  "business-skills": "Business Skills",
  "emerging-tech": "Emerging Technologies",
  "sustainability": "Sustainability",
  "specialized": "Specialized Domains",
  "diploma": "Advanced Diplomas",
  "intensive": "Intensive Programs",
}

export const bootcampsData: Bootcamp[] = [
  // Short-Term Courses
  {
    id: "exec-ai-leadership",
    title: "Executive AI Leadership Mastery",
    duration: "2 weeks",
    month: "December",
    category: "executive-leadership",
    type: "short-term",
    description: "Strategic AI application and peer networking for C-suite executives",
    highlights: ["AI Strategy", "Executive Networking", "Digital Transformation"],
    takeaways: [
      "Develop AI-driven business strategies",
      "Lead digital transformation initiatives",
      "Build executive AI networks",
      "Understand AI ethics and governance"
    ],
  },
  {
    id: "ai-agents-csuite",
    title: "AI Agents for C-Suite",
    duration: "2 weeks",
    month: "January",
    category: "executive-leadership",
    type: "short-term",
    description: "Leverage AI agents for strategic decision-making at the executive level",
    highlights: ["AI Agents", "Strategic Planning", "Executive Tools"],
  },
  {
    id: "rural-digital-transformation",
    title: "Rural Digital Transformation",
    duration: "2 weeks",
    month: "December",
    category: "professional-dev",
    type: "short-term",
    description: "Focus on agri-tech and digital financial inclusion for rural development",
    highlights: ["Agri-Tech", "Financial Inclusion", "Rural Development"],
  },
  {
    id: "quantum-computing-qiskit",
    title: "Quantum Computing with Qiskit",
    duration: "16 hours 45 minutes",
    month: "Ongoing",
    category: "emerging-tech",
    type: "short-term",
    description: "Master quantum gates, algorithms, and practical quantum computing with IBM Qiskit",
    highlights: ["Quantum Gates", "Quantum Algorithms", "Hands-on Practice"],
    takeaways: [
      "Build quantum circuits with Qiskit",
      "Implement Grover's and Shor's algorithms",
      "Run simulations on quantum hardware",
      "Apply quantum computing to real problems"
    ],
  },
  {
    id: "ai-healthcare-professionals",
    title: "AI for Healthcare Professionals",
    duration: "2 weeks",
    month: "January",
    category: "specialized",
    type: "short-term",
    description: "Apply AI technologies in healthcare settings and medical decision-making",
    highlights: ["Medical AI", "Healthcare Tech", "Clinical Applications"],
  },
  {
    id: "ai-education-teachers",
    title: "AI for Education & Teachers",
    duration: "2 weeks",
    month: "February",
    category: "specialized",
    type: "short-term",
    description: "Integrate AI tools in educational practices and curriculum development",
    highlights: ["EdTech", "AI Tools", "Curriculum Design"],
  },
  {
    id: "ai-legal-compliance",
    title: "AI for Legal & Compliance Professionals",
    duration: "2 weeks",
    month: "March",
    category: "professional-dev",
    type: "short-term",
    description: "AI applications in legal research, contract analysis, and compliance",
    highlights: ["Legal Tech", "Contract Analysis", "Compliance AI"],
  },
  {
    id: "ai-finance-banking",
    title: "AI for Finance & Banking",
    duration: "2 weeks",
    month: "April",
    category: "professional-dev",
    type: "short-term",
    description: "AI-driven financial analysis, risk management, and banking automation",
    highlights: ["FinTech", "Risk Management", "Banking AI"],
    takeaways: [
      "Automate financial analysis with AI",
      "Build fraud detection systems",
      "Implement risk assessment models",
      "Use AI for customer service automation"
    ],
  },
  {
    id: "ai-marketing-sales",
    title: "AI for Marketing & Sales",
    duration: "2 weeks",
    month: "May",
    category: "business-skills",
    type: "short-term",
    description: "AI-powered marketing strategies, customer insights, and sales automation",
    highlights: ["Marketing AI", "Sales Automation", "Customer Analytics"],
  },
  {
    id: "ai-hr-management",
    title: "AI for HR & Talent Management",
    duration: "2 weeks",
    month: "June",
    category: "professional-dev",
    type: "short-term",
    description: "AI tools for recruitment, employee engagement, and talent development",
    highlights: ["HR Tech", "Talent Analytics", "Employee Management"],
  },
  {
    id: "ai-manufacturing-operations",
    title: "AI for Manufacturing & Operations",
    duration: "2 weeks",
    month: "July",
    category: "specialized",
    type: "short-term",
    description: "AI in production optimization, quality control, and supply chain",
    highlights: ["Smart Manufacturing", "Quality Control", "Operations AI"],
  },
  {
    id: "ai-retail-ecommerce",
    title: "AI for Retail & E-commerce",
    duration: "2 weeks",
    month: "August",
    category: "business-skills",
    type: "short-term",
    description: "AI-driven customer experience, inventory management, and personalization",
    highlights: ["Retail Tech", "E-commerce AI", "Personalization"],
  },
  {
    id: "ai-logistics-supply-chain",
    title: "AI for Logistics & Supply Chain",
    duration: "2 weeks",
    month: "September",
    category: "specialized",
    type: "short-term",
    description: "AI optimization for logistics, route planning, and supply chain management",
    highlights: ["Logistics AI", "Route Optimization", "Supply Chain"],
  },
  {
    id: "ai-real-estate",
    title: "AI for Real Estate",
    duration: "2 weeks",
    month: "October",
    category: "specialized",
    type: "short-term",
    description: "AI applications in property valuation, market analysis, and customer matching",
    highlights: ["PropTech", "Market Analysis", "Property AI"],
  },
  {
    id: "green-finance-sustainability",
    title: "Green Finance & Sustainability",
    duration: "2 weeks",
    month: "January",
    category: "sustainability",
    type: "short-term",
    description: "Sustainable finance practices and green investment strategies",
    highlights: ["Green Finance", "ESG Investing", "Sustainability"],
  },
  {
    id: "climate-mitigation-tech",
    title: "Climate Mitigation Technologies",
    duration: "2 weeks",
    month: "February",
    category: "sustainability",
    type: "short-term",
    description: "Technologies and strategies for climate change mitigation",
    highlights: ["Climate Tech", "Carbon Reduction", "Environmental Solutions"],
  },
  {
    id: "ev-battery-technologies",
    title: "EV & Battery Technologies",
    duration: "2 weeks",
    month: "March",
    category: "sustainability",
    type: "short-term",
    description: "Electric vehicle technology and advanced battery systems",
    highlights: ["EV Tech", "Battery Systems", "Electric Mobility"],
  },
  {
    id: "renewable-energy-systems",
    title: "Renewable Energy Systems",
    duration: "2 weeks",
    month: "April",
    category: "sustainability",
    type: "short-term",
    description: "Solar, wind, and other renewable energy technologies",
    highlights: ["Solar Energy", "Wind Power", "Clean Energy"],
  },
  {
    id: "drone-technology-applications",
    title: "Drone Technology & Applications",
    duration: "2 weeks",
    month: "May",
    category: "emerging-tech",
    type: "short-term",
    description: "UAV technology, operations, and commercial applications",
    highlights: ["UAV Operations", "Drone Tech", "Aerial Applications"],
    takeaways: [
      "Operate drones safely and legally",
      "Plan aerial survey missions",
      "Analyze drone-captured data",
      "Explore commercial drone applications"
    ],
  },
  {
    id: "robotics-automation",
    title: "Robotics & Automation",
    duration: "2 weeks",
    month: "June",
    category: "emerging-tech",
    type: "short-term",
    description: "Industrial robotics, automation systems, and intelligent machines",
    highlights: ["Industrial Robotics", "Automation", "Smart Systems"],
  },
  {
    id: "metaverse-virtual-worlds",
    title: "Metaverse & Virtual Worlds",
    duration: "2 weeks",
    month: "July",
    category: "emerging-tech",
    type: "short-term",
    description: "Creating and navigating metaverse platforms and virtual environments",
    highlights: ["Metaverse", "VR/AR", "Virtual Worlds"],
  },
  {
    id: "blockchain-web3",
    title: "Blockchain & Web3",
    duration: "2 weeks",
    month: "August",
    category: "emerging-tech",
    type: "short-term",
    description: "Blockchain technology, smart contracts, and decentralized applications",
    highlights: ["Blockchain", "Smart Contracts", "Web3"],
  },
  {
    id: "iot-smart-devices",
    title: "IoT & Smart Devices",
    duration: "2 weeks",
    month: "September",
    category: "emerging-tech",
    type: "short-term",
    description: "Internet of Things, connected devices, and smart systems",
    highlights: ["IoT", "Smart Devices", "Connected Systems"],
  },
  {
    id: "cybersecurity-fundamentals",
    title: "Cybersecurity Fundamentals",
    duration: "2 weeks",
    month: "October",
    category: "professional-dev",
    type: "short-term",
    description: "Essential cybersecurity practices, threat detection, and data protection",
    highlights: ["Security", "Threat Detection", "Data Protection"],
  },
  {
    id: "data-analytics-visualization",
    title: "Data Analytics & Visualization",
    duration: "2 weeks",
    month: "November",
    category: "professional-dev",
    type: "short-term",
    description: "Data analysis techniques and effective visualization strategies",
    highlights: ["Data Analysis", "Visualization", "Business Intelligence"],
  },
  {
    id: "cloud-computing-aws",
    title: "Cloud Computing with AWS",
    duration: "2 weeks",
    month: "December",
    category: "emerging-tech",
    type: "short-term",
    description: "AWS cloud services, architecture, and deployment strategies",
    highlights: ["AWS", "Cloud Architecture", "DevOps"],
  },
  {
    id: "digital-marketing-strategy",
    title: "Digital Marketing Strategy",
    duration: "2 weeks",
    month: "January",
    category: "business-skills",
    type: "short-term",
    description: "Comprehensive digital marketing planning and execution",
    highlights: ["Digital Marketing", "Strategy", "Online Presence"],
  },
  {
    id: "social-media-management",
    title: "Social Media Management",
    duration: "1 week",
    month: "February",
    category: "business-skills",
    type: "short-term",
    description: "Social media strategy, content creation, and community management",
    highlights: ["Social Media", "Content Strategy", "Community Building"],
  },
  {
    id: "content-creation-strategy",
    title: "Content Creation & Strategy",
    duration: "1 week",
    month: "March",
    category: "business-skills",
    type: "short-term",
    description: "Creating engaging content and developing content marketing strategies",
    highlights: ["Content Marketing", "Copywriting", "Brand Voice"],
  },
  {
    id: "freelancing-success",
    title: "Freelancing Success",
    duration: "1 week",
    month: "April",
    category: "business-skills",
    type: "short-term",
    description: "Building a successful freelance career and managing clients",
    highlights: ["Freelancing", "Client Management", "Business Development"],
  },
  {
    id: "startup-fundamentals",
    title: "Startup Fundamentals",
    duration: "2 weeks",
    month: "May",
    category: "business-skills",
    type: "short-term",
    description: "Essential knowledge for launching and growing a startup",
    highlights: ["Entrepreneurship", "Startup Strategy", "Business Planning"],
  },
  {
    id: "msme-digital-awareness",
    title: "MSME Digital Awareness",
    duration: "1 week",
    month: "June",
    category: "business-skills",
    type: "short-term",
    description: "Digital transformation strategies for small and medium enterprises",
    highlights: ["Digital Transformation", "MSME", "Business Digitalization"],
  },
  {
    id: "agritech-innovations",
    title: "AgriTech Innovations",
    duration: "2 weeks",
    month: "July",
    category: "specialized",
    type: "short-term",
    description: "Technology applications in agriculture and farming",
    highlights: ["AgriTech", "Smart Farming", "Agricultural Innovation"],
  },
  {
    id: "healthtech-solutions",
    title: "HealthTech Solutions",
    duration: "2 weeks",
    month: "August",
    category: "specialized",
    type: "short-term",
    description: "Digital health technologies and healthcare innovation",
    highlights: ["HealthTech", "Digital Health", "Medical Innovation"],
  },
  {
    id: "edtech-digital-learning",
    title: "EdTech & Digital Learning",
    duration: "2 weeks",
    month: "September",
    category: "specialized",
    type: "short-term",
    description: "Educational technology and online learning platforms",
    highlights: ["EdTech", "E-Learning", "Educational Innovation"],
  },
  {
    id: "fintech-innovations",
    title: "FinTech Innovations",
    duration: "2 weeks",
    month: "October",
    category: "specialized",
    type: "short-term",
    description: "Financial technology and digital payment systems",
    highlights: ["FinTech", "Digital Payments", "Financial Innovation"],
  },
  {
    id: "smart-cities-urban-tech",
    title: "Smart Cities & Urban Tech",
    duration: "2 weeks",
    month: "November",
    category: "specialized",
    type: "short-term",
    description: "Urban technology solutions and smart city infrastructure",
    highlights: ["Smart Cities", "Urban Planning", "City Tech"],
  },
  {
    id: "autonomous-vehicles",
    title: "Autonomous Vehicles",
    duration: "2 weeks",
    month: "December",
    category: "emerging-tech",
    type: "short-term",
    description: "Self-driving technology and autonomous mobility systems",
    highlights: ["Autonomous Driving", "Vehicle AI", "Smart Mobility"],
  },
  {
    id: "5g-connectivity",
    title: "5G & Next-Gen Connectivity",
    duration: "1 week",
    month: "January",
    category: "emerging-tech",
    type: "short-term",
    description: "5G technology, applications, and future connectivity",
    highlights: ["5G", "Network Technology", "Connectivity"],
  },
  {
    id: "edge-computing",
    title: "Edge Computing",
    duration: "1 week",
    month: "February",
    category: "emerging-tech",
    type: "short-term",
    description: "Distributed computing and edge infrastructure",
    highlights: ["Edge Computing", "Distributed Systems", "Low Latency"],
  },
  {
    id: "ai-ethics-governance",
    title: "AI Ethics & Governance",
    duration: "1 week",
    month: "March",
    category: "professional-dev",
    type: "short-term",
    description: "Ethical AI development and governance frameworks",
    highlights: ["AI Ethics", "Governance", "Responsible AI"],
  },
  {
    id: "data-privacy-gdpr",
    title: "Data Privacy & GDPR",
    duration: "1 week",
    month: "April",
    category: "professional-dev",
    type: "short-term",
    description: "Data protection regulations and privacy compliance",
    highlights: ["Data Privacy", "GDPR", "Compliance"],
  },
  {
    id: "project-management-agile",
    title: "Project Management & Agile",
    duration: "2 weeks",
    month: "May",
    category: "professional-dev",
    type: "short-term",
    description: "Agile methodologies and modern project management",
    highlights: ["Agile", "Scrum", "Project Management"],
  },
  {
    id: "leadership-team-building",
    title: "Leadership & Team Building",
    duration: "1 week",
    month: "June",
    category: "professional-dev",
    type: "short-term",
    description: "Leadership skills and effective team management",
    highlights: ["Leadership", "Team Management", "Communication"],
  },
  {
    id: "innovation-design-thinking",
    title: "Innovation & Design Thinking",
    duration: "1 week",
    month: "July",
    category: "professional-dev",
    type: "short-term",
    description: "Design thinking methodology and innovation frameworks",
    highlights: ["Design Thinking", "Innovation", "Problem Solving"],
  },
  {
    id: "business-analytics",
    title: "Business Analytics",
    duration: "2 weeks",
    month: "August",
    category: "professional-dev",
    type: "short-term",
    description: "Business intelligence and analytics for decision-making",
    highlights: ["Business Intelligence", "Analytics", "Data-Driven Decisions"],
  },
  {
    id: "change-management",
    title: "Change Management",
    duration: "1 week",
    month: "September",
    category: "professional-dev",
    type: "short-term",
    description: "Managing organizational change and transformation",
    highlights: ["Change Management", "Transformation", "Organizational Development"],
  },

  // Long-Term Programs
  {
    id: "diploma-digital-entrepreneurship",
    title: "Diploma in Digital Entrepreneurship",
    duration: "6 months",
    month: "January - June",
    category: "diploma",
    type: "long-term",
    description: "Comprehensive program covering digital business models, startup strategies, and entrepreneurship",
    highlights: ["Business Models", "Startup Strategy", "Digital Marketing", "Funding"],
    takeaways: [
      "Launch and scale digital businesses",
      "Master lean startup methodologies",
      "Develop go-to-market strategies",
      "Pitch to investors effectively",
      "Build sustainable business models"
    ],
  },
  {
    id: "diploma-ev-battery-tech",
    title: "Diploma in EV & Battery Technologies",
    duration: "6 months",
    month: "February - July",
    category: "diploma",
    type: "long-term",
    description: "In-depth study of electric vehicle systems and battery technologies",
    highlights: ["EV Systems", "Battery Chemistry", "Charging Infrastructure", "Smart Mobility"],
  },
  {
    id: "advanced-digital-entrepreneurship",
    title: "Advanced Digital Entrepreneurship with AI Agents",
    duration: "6 months",
    month: "March - August",
    category: "diploma",
    type: "long-term",
    description: "Advanced entrepreneurship with focus on AI agents and automation",
    highlights: ["AI Agents", "Business Automation", "Scaling Strategies", "AI Integration"],
  },
  {
    id: "data-science-professionals",
    title: "Data Science for Professionals",
    duration: "3 months",
    month: "April - June",
    category: "intensive",
    type: "long-term",
    description: "Comprehensive data science program covering ML, statistics, and real-world applications",
    highlights: ["Machine Learning", "Statistical Analysis", "Data Engineering", "Projects"],
    takeaways: [
      "Build ML models from scratch",
      "Master Python, Pandas, and Scikit-learn",
      "Perform statistical analysis and hypothesis testing",
      "Create data pipelines and workflows",
      "Deploy models to production"
    ],
  },
  {
    id: "ml-aviation",
    title: "Machine Learning in Aviation",
    duration: "3 months",
    month: "May - July",
    category: "intensive",
    type: "long-term",
    description: "Specialized ML applications for aviation industry",
    highlights: ["Aviation AI", "Predictive Maintenance", "Flight Optimization", "Safety Systems"],
  },
  {
    id: "diploma-quantum-computing",
    title: "Diploma in Quantum Computing",
    duration: "6 months",
    month: "June - November",
    category: "diploma",
    type: "long-term",
    description: "Advanced quantum computing theory and practical applications",
    highlights: ["Quantum Algorithms", "Quantum Hardware", "Research Projects", "Industry Applications"],
  },
  {
    id: "project-management-professional",
    title: "Project Management Professional",
    duration: "3 months",
    month: "July - September",
    category: "intensive",
    type: "long-term",
    description: "PMP certification preparation and advanced project management",
    highlights: ["PMP Prep", "Agile/Scrum", "Risk Management", "Stakeholder Management"],
  },
  {
    id: "diploma-ai-ml",
    title: "Diploma in AI & Machine Learning",
    duration: "6 months",
    month: "August - January",
    category: "diploma",
    type: "long-term",
    description: "Comprehensive AI/ML program from fundamentals to advanced applications",
    highlights: ["Deep Learning", "NLP", "Computer Vision", "MLOps", "Capstone Project"],
    takeaways: [
      "Build neural networks with TensorFlow and PyTorch",
      "Develop NLP applications and chatbots",
      "Create computer vision systems",
      "Implement MLOps best practices",
      "Complete industry-grade capstone project"
    ],
  },
  {
    id: "cybersecurity-specialist",
    title: "Cybersecurity Specialist Program",
    duration: "6 months",
    month: "September - February",
    category: "diploma",
    type: "long-term",
    description: "Advanced cybersecurity training and certification",
    highlights: ["Network Security", "Ethical Hacking", "SOC Operations", "Incident Response"],
  },
  {
    id: "cloud-architect-professional",
    title: "Cloud Architect Professional",
    duration: "3 months",
    month: "October - December",
    category: "intensive",
    type: "long-term",
    description: "Multi-cloud architecture and cloud solution design",
    highlights: ["AWS/Azure/GCP", "Cloud Architecture", "DevOps", "Security"],
  },
  {
    id: "diploma-blockchain-developer",
    title: "Diploma in Blockchain Development",
    duration: "6 months",
    month: "November - April",
    category: "diploma",
    type: "long-term",
    description: "Blockchain development, smart contracts, and DApp creation",
    highlights: ["Blockchain Dev", "Smart Contracts", "DApps", "Web3", "Crypto"],
  },
  {
    id: "full-stack-developer",
    title: "Full Stack Developer Program",
    duration: "6 months",
    month: "December - May",
    category: "diploma",
    type: "long-term",
    description: "Comprehensive full-stack web development training",
    highlights: ["Frontend", "Backend", "Databases", "DevOps", "Projects"],
    takeaways: [
      "Build full-stack web applications",
      "Master React, Node.js, and databases",
      "Implement RESTful APIs and GraphQL",
      "Deploy applications with CI/CD",
      "Work on real client projects"
    ],
  },
  {
    id: "ux-ui-design-specialist",
    title: "UX/UI Design Specialist",
    duration: "3 months",
    month: "January - March",
    category: "intensive",
    type: "long-term",
    description: "User experience and interface design mastery",
    highlights: ["UX Research", "UI Design", "Prototyping", "User Testing", "Portfolio"],
  },
  {
    id: "digital-marketing-mastery",
    title: "Digital Marketing Mastery",
    duration: "3 months",
    month: "February - April",
    category: "intensive",
    type: "long-term",
    description: "Advanced digital marketing strategies and analytics",
    highlights: ["SEO/SEM", "Social Media", "Content Marketing", "Analytics", "Campaigns"],
  },
  {
    id: "diploma-robotics-automation",
    title: "Diploma in Robotics & Automation",
    duration: "6 months",
    month: "March - August",
    category: "diploma",
    type: "long-term",
    description: "Industrial robotics, automation systems, and AI integration",
    highlights: ["Robot Programming", "Automation", "AI Integration", "Industry 4.0"],
  },
  {
    id: "sustainable-energy-systems",
    title: "Sustainable Energy Systems Program",
    duration: "6 months",
    month: "April - September",
    category: "diploma",
    type: "long-term",
    description: "Renewable energy technologies and sustainable systems design",
    highlights: ["Solar/Wind", "Energy Storage", "Grid Integration", "Sustainability"],
  },
  {
    id: "iot-solutions-architect",
    title: "IoT Solutions Architect",
    duration: "3 months",
    month: "May - July",
    category: "intensive",
    type: "long-term",
    description: "IoT architecture, device management, and solution design",
    highlights: ["IoT Architecture", "Edge Computing", "Security", "Cloud Integration"],
  },
]
